/* ケロちゃん もぐもぐ in every language: [Tiếng Việt, English, 한국어] (see js/lang.js). */
Lang.add({
  'だれが あそぶ？': ['Ai chơi nào?', 'Who is playing?', '누가 할래?'],
  'なまえなし': ['Chưa có tên', 'No name', '이름 없음'],
  'とじる': ['Đóng', 'Close', '닫기'],
  // title
  'ケロちゃん もぐもぐ': ['Kero Măm Măm', 'Kero Munch Munch', '케로 냠냠'],
  'ロープを きって おやつを あげよう！': ['Cắt dây, cho Kero ăn bánh kẹo nào!', 'Cut the rope and feed Kero a treat!', '줄을 잘라서 케로에게 간식을 주자!'],
  'メニューに もどる': ['Về menu', 'Back to the menu', '메뉴로 돌아가기'],
  'ホームに ついか': ['Thêm vào màn hình', 'Add to Home', '홈 화면에 추가'],
  'こうかおん': ['Âm thanh', 'Sound effects', '효과음'],
  'おんがく': ['Nhạc', 'Music', '음악'],
  'おと': ['Âm thanh', 'Sound', '소리'],
  'あそぶ': ['Chơi', 'Play', '놀자'],
  'おみせ': ['Cửa hàng', 'Shop', '가게'],
  '管理者メニュー': ['Menu quản lý', 'Admin menu', '관리자 메뉴'],
  'もどる': ['Quay lại', 'Back', '뒤로'],
  // worlds and stages
  'ワールドを えらぼう': ['Chọn thế giới', 'Pick a world', '월드를 골라 봐'],
  'ワールド {n}': ['Thế giới {n}', 'World {n}', '월드 {n}'],
  'ステージ': ['Màn chơi', 'Stages', '스테이지'],
  'ヒント': ['Gợi ý', 'Hint', '힌트'],
  'もういちど': ['Chơi lại', 'Try again', '다시 하기'],
  'つぎへ': ['Tiếp theo', 'Next', '다음'],
  'キャンディの はらっぱ': ['Cánh đồng kẹo', 'Candy Meadow', '사탕 들판'],
  'いちごの おか': ['Đồi dâu tây', 'Strawberry Hill', '딸기 언덕'],
  'ドーナツの そら': ['Bầu trời donut', 'Donut Sky', '도넛 하늘'],
  'クッキーの もり': ['Rừng bánh quy', 'Cookie Forest', '쿠키 숲'],
  'にじいろ パーティー': ['Bữa tiệc cầu vồng', 'Rainbow Party', '무지개 파티'],
  'キャンディの まきば': ['Đồng cỏ kẹo', 'Candy Pasture', '사탕 목장'],
  'いちごの おはなばたけ': ['Vườn hoa dâu tây', 'Strawberry Garden', '딸기 꽃밭'],
  'ドーナツの ふしぎな そら': ['Bầu trời donut kỳ diệu', 'Magic Donut Sky', '신기한 도넛 하늘'],
  'クッキーの くるくる もり': ['Rừng bánh quy xoay xoay', 'Twirly Cookie Forest', '빙글빙글 쿠키 숲'],
  'にじいろ おまつり': ['Lễ hội cầu vồng', 'Rainbow Festival', '무지개 축제'],
  'キャンディの ぼうけん': ['Chuyến phiêu lưu kẹo', 'Candy Adventure', '사탕 대모험'],
  'いちごの おしろ': ['Lâu đài dâu tây', 'Strawberry Castle', '딸기 성'],
  'ドーナツの ほしぞら': ['Trời sao donut', 'Donut Starry Sky', '도넛 별하늘'],
  'クッキーの おおきな き': ['Cây bánh quy khổng lồ', 'Big Cookie Tree', '커다란 쿠키 나무'],
  'にじいろ グランプリ': ['Giải đua cầu vồng', 'Rainbow Grand Prix', '무지개 그랑프리'],
  // tips
  'ゆびで ロープを スーッと きってね': ['Lướt ngón tay để cắt dây nhé', 'Swipe your finger to cut the rope', '손가락으로 줄을 쓱 잘라 봐'],
  'ロープが 2ほん。きる じゅんばんを かんがえてね': ['Có 2 sợi dây. Nghĩ xem cắt sợi nào trước nhé', 'Two ropes! Think which one to cut first', '줄이 2개야. 자르는 순서를 생각해 봐'],
  'ゆらゆら…いい ところで きってね': ['Đung đưa… cắt đúng lúc nhé', 'Swing, swing… cut at the right moment', '흔들흔들… 좋은 때에 잘라 봐'],
  'ほしも ぜんぶ あつめられるかな？': ['Lấy được hết các ngôi sao không nào?', 'Can you get all the stars too?', '별도 전부 모을 수 있을까?'],
  'しゃぼんだまに はいると ふわふわ。タッチで われるよ': ['Vào bong bóng là bay lơ lửng. Chạm vào để làm vỡ', 'Bubbles float up. Tap to pop them', '비눗방울에 들어가면 둥실둥실. 터치하면 터져'],
  'くもを タッチすると ふーっ！と かぜが でるよ': ['Chạm vào đám mây, gió sẽ thổi phù phù!', 'Tap a cloud to blow a puff of wind!', '구름을 터치하면 후~ 바람이 나와'],
  'ゼリーに あたると ぽよーんと はねるよ': ['Chạm vào thạch sẽ nảy lên tưng tưng', 'Jelly makes things bounce — boing!', '젤리에 닿으면 통~ 하고 튀어 올라'],
  'ピンに ちかづくと ロープが くっつくよ': ['Đến gần cái ghim, dây sẽ dính vào', 'Get close to a pin and a rope sticks to it', '핀에 가까이 가면 줄이 붙어'],
  'ピンが うごくよ。よく みて きってね': ['Cái ghim di chuyển đấy. Nhìn kỹ rồi cắt nhé', 'The pin moves. Watch closely, then cut', '핀이 움직여. 잘 보고 잘라 봐'],
  'トゲトゲに さわると おやつが われちゃう！': ['Chạm vào gai là kẹo vỡ mất!', 'Spikes break the treat — watch out!', '가시에 닿으면 간식이 깨져 버려!'],
  'ぼうしに はいると、おなじ いろの ぼうしから でてくるよ': ['Vào một chiếc mũ sẽ chui ra từ chiếc mũ cùng màu', 'In one hat, out of the hat of the same colour', '모자에 들어가면 같은 색 모자에서 나와'],
  'くるくる まわる トゲに きをつけて。すきまを ねらってね': ['Cẩn thận gai quay tròn. Canh khe hở nhé', 'Watch the spinning spikes. Aim for the gap', '빙글빙글 도는 가시를 조심해. 틈을 노려 봐'],
  // clear
  'かんぺき！': ['Hoàn hảo!', 'Perfect!', '완벽해!'],
  'すごい！': ['Giỏi quá!', 'Great!', '대단해!'],
  'やったね！': ['Làm được rồi!', 'You did it!', '해냈다!'],
  'ぜんぶ クリア！': ['Qua hết rồi!', 'All clear!', '모두 클리어!'],
  'ワールド クリア！': ['Xong thế giới!', 'World clear!', '월드 클리어!'],
  // shop
  'ケロちゃん': ['Kero', 'Kero', '케로'],
  'ミミちゃん': ['Mimi', 'Mimi', '미미'],
  'ニャーちゃん': ['Meo Meo', 'Meow', '야옹이'],
  'ワンちゃん': ['Gâu Gâu', 'Woof', '멍멍이'],
  '★を つかって おともだちを ふやそう！': ['Dùng ★ để có thêm bạn mới nhé!', 'Use your ★ to make new friends!', '★로 새 친구를 만들자!'],
  'つかってる': ['Đang chọn', 'Chosen', '함께하는 중'],
  'えらぶ': ['Chọn', 'Choose', '고르기'],
  '{star}{price} で かう': ['Mua {star}{price}', 'Buy {star}{price}', '{star}{price}에 사기'],
  'あと ★{n} で かえるよ': ['Cần thêm ★{n} nữa là mua được', '{n} more ★ to buy it', '★{n}개만 더 모으면 살 수 있어'],
  '{name}を<br>{star}{price} で かう？': ['Mua {name}<br>với {star}{price} nhé?', 'Buy {name}<br>for {star}{price}?', '{name}를<br>{star}{price}에 살까?'],
  '{name}が なかまに なったよ！': ['{name} đã thành bạn rồi!', '{name} is your friend now!', '{name}가 친구가 되었어!'],
  'やめる': ['Thôi', 'Cancel', '취소'],
  'かう': ['Mua', 'Buy', '살래'],
  // admin (for grown-ups)
  '管理者パスワード': ['Mật khẩu quản lý', 'Admin password', '관리자 비밀번호'],
  'けす': ['Xóa', 'Del', '지우기'],
  '閉じる': ['Đóng', 'Close', '닫기'],
  '全ステージ解放：オン': ['Mở khóa mọi màn: Bật', 'Unlock all stages: On', '모든 스테이지 열기: 켬'],
  '全ステージ解放：オフ': ['Mở khóa mọi màn: Tắt', 'Unlock all stages: Off', '모든 스테이지 열기: 끔'],
  '記録をリセット': ['Xóa kỷ lục', 'Reset records', '기록 초기화'],
  'もう一度押すと消えます': ['Nhấn lần nữa để xóa', 'Press again to erase', '한 번 더 누르면 지워져요'],
  'あつめた★ {got}　つかった★ {spent}': ['★ đã nhặt: {got}　★ đã dùng: {spent}', '★ collected: {got}　★ spent: {spent}', '모은 ★ {got}　쓴 ★ {spent}']
});

// The big title, one line per row (each letter hops on its own).
var GAME_LOGO = { ja: ['ケロちゃん', 'もぐもぐ'], vi: ['Kero', 'Măm Măm'], en: ['Kero', 'Munch Munch'], ko: ['케로', '냠냠'] };
